# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NuGet Package Release Build

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    types:
      - opened
    branches:
      - 'releases/**'

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Harvest version variables
      run: |
          echo 'N2H_BUILD_NUMBER=${{ env.BUILD_NUMBER }}' >> $GITHUB_ENV
      env:
        BUILD_NUMBER: ${{ github.run_number }}-${{ github.run_attempt }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
          dotnet build --no-restore --configuration Release -p:BuildNumber=${{ env.N2H_BUILD_NUMBER }}

    - name: Pack
      run: |
          dotnet pack ./Net2HassMqtt/Net2HassMqtt.csproj --no-build --no-restore --configuration Release


    - name: Archive NuGet package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: Net2HassMqtt/bin/**/*.nupkg
        compression-level: 0
        if-no-files-found: error


